C COUNT ROWS IN BINARY DATA
      INTEGER FUNCTION COUNTR(FN)
        IMPLICIT NONE
        CHARACTER(16) FN
        INTEGER V,V2
        OPEN(11,FILE=FN,ACCESS='DIRECT',RECL=8)
         COUNTR=1
10       READ(11,REC=COUNTR,ERR=20) V,V2
         COUNTR=COUNTR+1
         GOTO 10
20      CONTINUE
        CLOSE(11) 
        COUNTR=COUNTR-1
        RETURN
      END


